import random

subject_qualifiers = (
        "shy",
        "mature",
        "busty",
        "hot",
        "horny",
        "ebony",
        "quiet",
        "excited",
        "naughty",
        "bad",
        "cheating",
        "beautifull",
        "gorgeous",
        "drunk",
        "emo",
        "fat",
        "chubby",
        "goth",
        "lingery wearing",
        "latex enthousiast",
        "placid",
        "energic",
        "slutty",
        "sweaty",
        "curvy",
        )

subjects = (
        "teen",
        "doll",
        "brunette",
        "blonde",
        "midget",
        "milf",
        "bitch",
        "babe",
        "sister",
        "step-mom",
        "vixen",
        "secretary",
        "real estate agent",
        "teacher",
        "student",
        "schoolgirl",
        "cheer leader",
        "asian tourist",
        "babysitter",
        "ex girlfriend",
        "nurse",
        "squirtter",
        "model",
        "granny",
        "furry",
        )

actions = (
        "receives anal",
        "get busted",
        "driven to bukakke",
        "taught double penetration",
        "fucked hard",
        "gently chocked",
        "punished",
        "forced into blow job",
        "pounded",
        "creampied",
        "ass raped",
        "eaten",
        "get her pussy wet",
        "shamed",
        "get an orgasm for the first time",
        "lead to loud climax",
        "offered best sex of her life",
        "worn out",
        "cured from boredom",
        "warmed up",
        "loved in and out",
        "generously oiled",
        "shocked and impressed",
        "decieved into giving it",
        "woke up roughly",
        "get sexy massage",
        "ridden to exhaustion",
        "turned into a lavish slave",
        "never submit to torture",
        "rebels against abuses",
        "taken in every possible way",
        "enjoy the 10 inches provided",
        )

actors = (
        "pawn shop owner",
        "corrupted cop",
        "dirty plumber",
        "big ass nigga",
        "sport coach" "her boss",
        "twisted psychiatrist",
        "ripped doctor",
        "crispy fire fighter",
        "smug playboy",
        "skinny geek",
        "eccentric millionaire",
        "airplane pilot",
        "movie star",
        "football team",
        "her big brother",
        "security guard",
        "hairy beast",
        "wasted guitard player",
        "hung indian immigrant",
        "a guy twice her size",
        "17 guys in a row",
        "her ideal man",
        "her secret prince charming",
        "weirdo albinos",
        "muscle giant",
        "the worst cook ever",
        "cable man",
        "more men that she can count",
        "two friendly brothers",
        "enrike strongsteel",
        )

contexts = (
        "on the beach",
        "in a cheap motel",
        "in the back of a van",
        "in airplane toilets",
        "for hours",
        "to pay back her depts",
        "for a stupid mistake",
        "and it gets better",
        "and ask for more",
        "because she could",
        "in exchange for a favor",
        "right next to her boyfriend",
        "as a reward",
        "hopping to get him back",
        "caught on security cam",
        "every monday",
        "in a barn",
        "but that's not all",
        "but she has a secret",
        "and she has a dick too",
        "before inviting her friend over",
        "while her father is watching",
        "with her ",
        "while auditing for a role",
        "to get her job back",
        "for an interview",
        "in exclusive sex tape",
        "again and again",
        ", begging to stop",
        "for a change",
        "for chrismas",
        "in public",
        "in a back alley",
        "during a concert",
        "on her death bed",
        )

punctuation = ("", "!", "!!", "...")


def get_title(subject_qualifiers, subjects, actions, actors, contexts):

    qualifier = random.choice(subject_qualifiers)
    subject = random.choice(subjects)
    action = random.choice(actions)
    actor = random.choice(actors)
    context = random.choice(contexts)

    return f"{qualifier} {subject} {action} by {actor} {context}".capitalize()


if __name__ == "__main__":
    print(
            get_title(
                subject_qualifiers=subject_qualifiers,
                subjects=subjects,
                actions=actions,
                actors=actors,
                contexts=contexts,
                )
            )
