#!/usr/bin/env sh

# File extension to check for changes
OBSERVE='dist'

# get a list of files changed by the merge
changes=`git diff --name-only HEAD@{1} HEAD`

prompt_user_with_diff()
{
    # first check if user configured mergetool
    mergetool=`git config --get merge.tool`
    if [[ -n "$mergetool" ]]; then
        prog=$mergetool
    else
        prog='vimdiff'
    fi

    distfile=$1
    configfile=${distfile%.*}

    echo "$1 has changed since the merge. Would you like to see the diff with ? [y n q]\n"
    read wanna_diff

}

while read -r line
do
    filename=$(basename "$line")
    extension=${filename##*.}
    if [[ "$extension" == "$OBSERVE" ]]; then
        prompt_user_with_diff $line
    fi
done <<< "$changes"


