#!/bin/sh

link (){
    rm -f $2
    ln -s $1 $2
}

link ~/.dotfiles/bashrc ~/.bashrc
link ~/.dotfiles/gitconfig ~/.gitconfig
link ~/.dotfiles/vim ~/.vim
link ~/.dotfiles/vimrc ~/.vimrc
link ~/.dotfiles/vimrc_git ~/.vimrc_git
link ~/.dotfiles/gvimrc ~/.gvimrc
link ~/.dotfiles/Xresources ~/.Xresources
link ~/.dotfiles/ackrc ~/.ackrc
link ~/.dotfiles/git-completion.bash ~/.git-completion.bash
link ~/.dotfiles/tmux.conf ~/.tmux.conf
link ~/.dotfiles/Xmodmap ~/.Xmodmap
link ~/.dotfiles/ctags ~/.ctags
link ~/.dotfiles/vimperatorrc ~/.vimperatorrc
link ~/.dotfiles/redshift.conf ~/.config/redshift.conf
