#!/bin/sh

link (){
    rm -f $2
    ln -s $1 $2
}

link ~/.dotfiles/bashrc ~/.bashrc
link ~/.dotfiles/gitconfig ~/.gitconfig
link ~/.dotfiles/vim ~/.vim
link ~/.dotfiles/vimrc ~/.vimrc
link ~/.dotfiles/gvimrc ~/.gvimrc
link ~/.dotfiles/Xdefaults ~/.Xdefaults
link ~/.dotfiles/ackrc ~/.ackrc
link ~/.dotfiles/git-completion.bash ~/.git-completion.bash
link ~/.dotfiles/tmux.conf ~/.tmux.conf
link ~/.dotfiles/xcolors ~/.xcolors
link ~/.dotfiles/Xmodmap ~/.Xmodmap
